# Generated by Django 3.1 on 2020-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('geo', models.CharField(max_length=15, verbose_name='Гео подписчика')),
                ('date_subscribe', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
            ],
        ),
    ]
