# Generated by Django 3.1 on 2020-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0002_auto_20201008_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
    ]
