# Generated by Django 3.1 on 2020-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0003_auto_20201019_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriber',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Телефон'),
        ),
    ]
