# Generated by Django 3.1 on 2020-10-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_distribution', '0004_auto_20201019_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriber',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
